//MS-VETERINARIA EN H2 DATABASE
CREATE TABLE VETERINARIAS(
    ID_VETERINARIA NUMBER, 
    NOMBRE NVARCHAR2(50), 
    DIRECCION NVARCHAR2(100), 
    TELEFONO NUMBER,
    CONSTRAINT ID_VETERINARIA_PK PRIMARY KEY(ID_VETERINARIA)
);

//MS-RESPONSABLES EN ORACLE USUARIO CURSO25
CREATE TABLE RESPONSABLES (
    ID_RESPONSABLE NUMBER,
    NOMBRE NVARCHAR2(50),
    CONTACTO NUMBER,
    VETERINARIA_ID NUMBER,
    CONSTRAINT ID_RESPONSABLE_PK PRIMARY KEY(ID_RESPONSABLE)
);

//MS-MASCOTAS EN MYSQL
CREATE TABLE MASCOTAS (
    ID_MASCOTA INT,
    NOMBRE VARCHAR(15) NOT NULL,
    RAZA VARCHAR(15),
    EDAD INT,
    RAZON_CITA VARCHAR(100),
    CLIENTE_ID INT,
    RESPONSABLE_ID INT,
    VETERINARIA_ID INT,
    CONSTRAINT ID_MASCOTA_PK PRIMARY KEY (ID_MASCOTA)
);

//MS-CLIENTES EN H2 DATABASE
CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR(50) NOT NULL,
    DIRECCION NVARCHAR(100),
    CONTACTO NUMBER
);